---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mybangjo/dev.mybangjo.com/
    - export COREPATH=/home/mybangjo/xentra-core/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R * $COREPATH
    - /bin/mkdir -p $DEPLOYPATH/tmp $COREPATH/tmp
    - /bin/touch $DEPLOYPATH/tmp/restart.txt $COREPATH/tmp/restart.txt
    - /usr/sbin/cloudlinux-selector restart --json --interpreter nodejs --user mybangjo --app-root /home/mybangjo/xentra-core || true
